#spring:
#  datasource:
#    #   \u6570\u636E\u6E90\u57FA\u672C\u914D\u7F6E
#    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
