spring:
  datasource:
    #   数据源基本配置
    url: jdbc:mysql://localhost:3306/springboot_cache?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  redis:
    host: localhost

#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
    # 执行sql脚本
#    initialization-mode: always

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml  # 指定全局配置文件的位置
#  mapper-locations: classpath:mybatis/mapper/*.xml    # 指定sql映射文件的位置
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.panshi.mapper: debug