# https://www.jianshu.com/p/12ec123d20e8
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root



# mybatis-plus相关配置
mybatis-plus:
  global-config:
    db-config:
      #主键类型  AUTO(0):"数据库ID自增", NONE(1):"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      column-underline: true
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#      #数据库类型
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:/mapper/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.panshi.mybatisplus01.entity

